apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: bunk8s-coordinator-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: bunk8s-coordinator-role
subjects:
- kind: ServiceAccount
  namespace: default
  name: {{ include "bunk8s-coordinator.serviceAccountName" . }}