apiVersion: v1
kind: Service
metadata:
  name: {{ include "bunk8s-coordinator.fullname" . }}
  labels:
    {{- include "bunk8s-coordinator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - nodePort: {{ .Values.service.nodePort }}
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "bunk8s-coordinator.selectorLabels" . | nindent 4 }}
